# Generated by Django 4.1.3 on 2022-11-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Related_Links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254, verbose_name='Unique FirstName')),
                ('last_name', models.CharField(max_length=254, verbose_name='Unique LastName')),
                ('nickname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('subject', models.CharField(max_length=254, verbose_name='Reason')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
