# Generated by Django 4.1.3 on 2022-11-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Related_Links', '0002_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='first_name',
            field=models.CharField(max_length=254, verbose_name='FirstName'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='last_name',
            field=models.CharField(max_length=254, verbose_name='LastName'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='subject',
            field=models.CharField(max_length=254, verbose_name='Subject'),
        ),
    ]
