# Generated by Django 4.1.3 on 2022-11-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Related_Links', '0003_alter_contact_us_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_heading', models.CharField(max_length=100, verbose_name='Heading')),
                ('Answer', models.TextField(verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Terms_of_Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, verbose_name='Heading')),
                ('Description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='privacy_and_policy',
            name='heading',
            field=models.CharField(max_length=100, verbose_name='Heading'),
        ),
    ]
