# Generated by Django 4.1.3 on 2022-11-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0002_alter_product_id_alter_productcategory_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
