# Generated by Django 4.1.3 on 2022-11-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0004_alter_product_name_alter_product_product_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='productapi.product_brands'),
            preserve_default=False,
        ),
    ]
