# Generated by Django 4.1.3 on 2022-11-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0005_alter_product_prod_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('trend_prod_desc', models.TextField(blank=True, verbose_name='Description')),
                ('trend_prod_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trend_prod_discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Trending_Items_product_name', to='productapi.product')),
            ],
        ),
        migrations.CreateModel(
            name='Exclusive_promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('excl_prod_desc', models.TextField(blank=True, verbose_name='Description')),
                ('excl_prod_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exclusive_promotions_product_name', to='productapi.productcategory')),
            ],
        ),
    ]
