# Generated by Django 4.1.3 on 2022-11-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0006_trending_items_exclusive_promotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Future_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('future_prod_desc', models.TextField(blank=True, verbose_name='Description')),
                ('future_prod_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Future_products_name', to='productapi.productcategory')),
            ],
        ),
    ]
