# Generated by Django 4.1.3 on 2022-11-07 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0008_alter_exclusive_promotions_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('feature_prod_desc', models.TextField(blank=True, verbose_name='Description')),
                ('feature_prod_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Future_products_name', to='productapi.productcategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_products_name', to='productapi.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Future_Products',
        ),
    ]
