# Generated by Django 4.1.3 on 2022-11-09 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0009_feature_products_delete_future_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='The start date of the subscription.')),
                ('status', models.CharField(help_text='The status of this subscription.', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MyStripeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stripe_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productapi.stripesubscription')),
            ],
        ),
    ]
